fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\App\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address: '%env(MAILER_USER_ADDRESS)%'
        sender_name: '%env(MAILER_USER_NAME)%'
    service:
        user_manager: sonata.user.orm.user_manager
        mailer: 'fos_user.mailer.twig_swift'
    group:
        group_class:   App\Entity\App\Group
        group_manager: sonata.user.orm.group_manager